services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: acamica-datawarehouse-backend
    container_name: backend
    ports:
      - 3500:3500
    environment:
      - PORT=$PORT
      - MONGO_URL=$MONGO_URL
      - DB_NAME=$DB_NAME
      - JWT_SECRET=$JWT_SECRET
    depends_on:
      - mongo
  mongo:
    image: mongo:6.0.2
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - ~/mongodb/data/db:/data/db
